#!/usr/bin/env node
// ══════════════════════════════════════════════════════════════
//  BEHANCE AUTO-FETCH SCRIPT (Node.js)
//  Run: node fetch-behance.js
//  Or schedule via GitHub Actions / Task Scheduler
//
//  Fetches ALL your Behance projects and generates projects.js
//  Works even without a browser — for local + CI use.
// ══════════════════════════════════════════════════════════════
const fs    = require('fs');
const path  = require('path');
const https = require('https');

// ── CONFIG (reads from config.js values, duplicated here for Node) ──
const USERNAME = 'ahmedhassanbahaa';
const API_KEY  = process.env.BEHANCE_API_KEY || ''; // set as env variable
const BASE     = 'https://api.behance.net/v2';
const OUT_FILE = path.join(__dirname, 'projects.js');

if (!API_KEY) {
  console.error('⚠  No API key. Set BEHANCE_API_KEY env variable.');
  console.error('   Example: BEHANCE_API_KEY=abc123 node fetch-behance.js');
  process.exit(1);
}

// ── HTTP helper ─────────────────────────────────────────────
function get(urlStr) {
  return new Promise((resolve, reject) => {
    https.get(urlStr, res => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch(e) { reject(new Error('JSON parse error: ' + data.slice(0,200))); }
      });
    }).on('error', reject);
  });
}

function apiUrl(path, params = {}) {
  const q = new URLSearchParams({ api_key: API_KEY, ...params });
  return `${BASE}${path}?${q}`;
}

// ── Category classifier ─────────────────────────────────────
function classify(fields = []) {
  const f = fields.join(' ').toLowerCase();
  if (/social|media|instagram|post/.test(f))      return 'Social';
  if (/print|poster|brochure|flyer/.test(f))      return 'Print';
  if (/brand|identity|logo|visual/.test(f))       return 'Branding';
  return 'Other';
}

// ── Transform ───────────────────────────────────────────────
function transform(raw, detail) {
  const images = [];
  if (detail?.modules) {
    detail.modules.forEach(m => {
      if (m.type === 'image' && m.src) images.push(m.src);
      if (m.type === 'media_collection') {
        (m.components||[]).forEach(c => { if(c.src) images.push(c.src); });
      }
    });
  }

  const colorObj = raw.colors?.[0];
  const color = colorObj ? `rgb(${colorObj.r},${colorObj.g},${colorObj.b})` : null;

  return {
    id:       raw.id,
    title:    raw.name,
    titleAr:  raw.name,
    desc:     detail?.description || raw.description || '',
    descAr:   detail?.description || raw.description || '',
    cover:    raw.covers?.['404']  || raw.covers?.original || '',
    coverLg:  raw.covers?.original || raw.covers?.['808']  || raw.covers?.['404'] || '',
    images,
    url:      raw.url,
    year:     new Date((raw.published_on || Date.now()/1000) * 1000).getFullYear(),
    views:    raw.stats?.views         || 0,
    likes:    raw.stats?.appreciations || 0,
    tags:     raw.fields || [],
    tagsAr:   raw.fields || [],
    cat:      classify(raw.fields),
    color,
    featured: !!raw.featured,
    wide:     false,
  };
}

// ── MAIN ────────────────────────────────────────────────────
async function main() {
  console.log(`\n📡 Fetching @${USERNAME} from Behance API…\n`);

  // 1. Projects list
  const projRes = await get(apiUrl(`/users/${USERNAME}/projects`, { per_page: 48, sort_by: 'published_on' }));
  const rawList = projRes.projects || [];
  console.log(`✓ Found ${rawList.length} projects`);

  // 2. Project details (full images + description) — up to 24
  const DETAIL_LIMIT = 24;
  const details = [];
  for (let i = 0; i < Math.min(rawList.length, DETAIL_LIMIT); i++) {
    try {
      const r = await get(apiUrl(`/projects/${rawList[i].id}`));
      details.push(r.project);
      process.stdout.write(`  Fetching details ${i+1}/${Math.min(rawList.length, DETAIL_LIMIT)}\r`);
      await new Promise(r => setTimeout(r, 150)); // gentle rate limiting
    } catch(e) {
      details.push(null);
    }
  }
  console.log('\n✓ Project details fetched');

  // 3. Transform
  const projects = rawList.map((p, i) => transform(p, details[i] ?? null));

  // 4. Write projects.js
  const output = [
    `// AUTO-GENERATED by fetch-behance.js — ${new Date().toISOString()}`,
    `// DO NOT EDIT MANUALLY — run: node fetch-behance.js`,
    `// Projects: ${projects.length}`,
    '',
    `const PROJECTS = ${JSON.stringify(projects, null, 2)};`,
  ].join('\n');

  fs.writeFileSync(OUT_FILE, output, 'utf8');
  console.log(`\n✅ projects.js updated — ${projects.length} projects written\n`);

  // 5. Summary
  const cats = {};
  projects.forEach(p => { cats[p.cat] = (cats[p.cat]||0)+1; });
  console.log('📊 Categories:');
  Object.entries(cats).forEach(([k,v]) => console.log(`   ${k}: ${v}`));
  console.log('');
}

main().catch(err => {
  console.error('\n❌ Error:', err.message);
  process.exit(1);
});
