// ═══════════════════════════════════════════════════════════════
//  PROJECTS.JS — Ahmed Hassan Bahaa Portfolio
// ═══════════════════════════════════════════════════════════════

function imgs(folder, prefix, count, ext) {
  ext = ext || 'png';
  var arr = [];
  for (var i = 1; i <= count; i++) {
    var n = i < 10 ? '0' + i : '' + i;
    arr.push('assets/projects/' + folder + '/images/' + prefix + '_' + n + '.' + ext);
  }
  return arr;
}

function flist(folder, files) {
  return files.map(function(f){ return 'assets/projects/' + folder + '/' + f; });
}

const PROJECTS = [

  // ══════════════════════════════════════════════════════
  //  سوشيال ميديا
  // ══════════════════════════════════════════════════════

  {
    id: 1,
    title: 'Social Media — Ebtikarhup',
    titleAr: 'سوشيال ميديا — إبتكار هب',
    desc: 'Full social media management for Ebtikarhup, a Saudi real estate company. Dynamic ads and promotional content across Instagram and Facebook.',
    descAr: 'إدارة سوشيال ميديا متكاملة لشركة إبتكار هب السعودية للعقارات. إعلانات ديناميكية ومحتوى ترويجي على انستقرام وفيسبوك.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Real Estate', 'Saudi Arabia'],
    tagsAr: ['سوشيال ميديا', 'عقارات', 'السعودية'],
    image:  'assets/projects/p1/Thumbnail - Size copy-opt.jpg',
    images: imgs('p1', 'Presentation1', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#0d0520 0%,#1a0a35 50%,#0f1040 100%)',
    saudi: true,
  },

  {
    id: 2,
    title: 'Social Media — Ebtikarhup Real Estate',
    titleAr: 'سوشيال ميديا — إبتكار هب عقارات',
    desc: 'Extended social media campaign for Ebtikarhup Real Estate, Saudi Arabia. Luxury property visuals and investor-targeted content.',
    descAr: 'حملة سوشيال ميديا موسعة لإبتكار هب عقارات السعودية. تصاميم عقارات فاخرة ومحتوى موجّه للمستثمرين.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Real Estate', 'Saudi Arabia'],
    tagsAr: ['سوشيال ميديا', 'عقارات', 'السعودية'],
    image:  'assets/projects/p2/Thumbnail - Size 2 copy-opt.jpg',
    images: imgs('p2', 'Presentation2', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#0d0520 0%,#1a0a35 50%,#0f1040 100%)',
    saudi: true,
  },

  {
    id: 3,
    title: 'Social Media — Al Fikr Consulting',
    titleAr: 'سوشيال ميديا — الفكر للاستشارات',
    desc: 'Social media content for Al Fikr Consulting, a business formation and legal advisory firm. Corporate posts with clear calls-to-action.',
    descAr: 'محتوى سوشيال ميديا لشركة الفكر للاستشارات وتأسيس الشركات. بوستات مؤسسية مع عبارات حث واضحة.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Consulting', 'Corporate'],
    tagsAr: ['سوشيال ميديا', 'استشارات', 'مؤسسي'],
    image:  'assets/projects/p3/Thumbnail - Size 3 copy-opt.jpg',
    images: imgs('p3', 'Presentation-3', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#0d0520 0%,#1a0a35 50%,#0f1040 100%)',
  },

  {
    id: 4,
    title: 'Social Media — Grasse Perfumes',
    titleAr: 'سوشيال ميديا — غراس للعطور',
    desc: 'Premium social media campaigns for Grasse Perfumes, an Emirati luxury fragrance brand. Rich product photography treatment and elegant copy.',
    descAr: 'حملات سوشيال ميديا لعلامة غراس الإماراتية الفاخرة للعطور. معالجة صور احترافية وكتابة إعلانية أنيقة.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Perfumes', 'Luxury', 'UAE'],
    tagsAr: ['سوشيال ميديا', 'عطور', 'فاخر', 'الإمارات'],
    image:  'assets/projects/p4/Thumbnail - Size 3 copy-opt.jpg',
    images: imgs('p4', 'Presentation-4', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#1a1000 0%,#2a1e04 50%,#120e00 100%)',
    uae: true,
  },

  {
    id: 17,
    title: 'Social Media — Grasse Perfumes Vol.2',
    titleAr: 'سوشيال ميديا — غراس للعطور Vol.2',
    desc: 'Second campaign series for Grasse Perfumes. Seasonal collections including Grasse Heart, Princess, and Leon fragrances.',
    descAr: 'السلسلة الثانية لحملات غراس للعطور. كولكشنات موسمية: غراس هارت، برينسيس، ليون.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Perfumes', 'UAE', 'Campaign'],
    tagsAr: ['سوشيال ميديا', 'عطور', 'الإمارات', 'حملة'],
    image:  'assets/projects/p5/Thumbnail - Size 5 copy-opt.jpg',
    images: imgs('p5', 'Presentation-5', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#1a1000 0%,#2a1e04 50%,#120e00 100%)',
    uae: true,
  },

  {
    id: 18,
    title: 'Social Media — Grasse Collections',
    titleAr: 'سوشيال ميديا — غراس كولكشنز',
    desc: 'Grasse luxury fragrance collections campaign. Featuring Real Summer, Season, Storm, Cannes, Alain and more.',
    descAr: 'حملة كولكشنات غراس الفاخرة. تشمل: ريال صمر، سيزون، ستورم، كان، ألان وغيرها.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Perfumes', 'Collections', 'UAE'],
    tagsAr: ['سوشيال ميديا', 'عطور', 'كولكشنات', 'الإمارات'],
    image:  'assets/projects/p6/Thumbnail - Size 7 copy-opt.jpg',
    images: imgs('p6', 'Presentation-7', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#1a1000 0%,#2a1e04 50%,#120e00 100%)',
    uae: true,
  },

  {
    id: 19,
    title: 'Social Media — Grasse UAE Edition',
    titleAr: 'سوشيال ميديا — غراس الإصدار الإماراتي',
    desc: 'Special UAE National Day edition campaign for Grasse Perfumes. Patriotic visuals with premium fragrance styling.',
    descAr: 'حملة إصدار اليوم الوطني الإماراتي لعلامة غراس. تصاميم وطنية بأسلوب العطور الفاخرة.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Perfumes', 'UAE National Day', 'UAE'],
    tagsAr: ['سوشيال ميديا', 'عطور', 'اليوم الوطني', 'الإمارات'],
    image:  'assets/projects/p8/Thumbnail - Size 8 copy-opt.jpg',
    images: imgs('p8', 'Presentation-8', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#1a1000 0%,#2a1e04 50%,#120e00 100%)',
    uae: true,
  },

  {
    id: 20,
    title: 'Social Media — Arabic Restaurant',
    titleAr: 'سوشيال ميديا — مطعم عربي',
    desc: 'Appetising social media content for a traditional Arabic restaurant. Warm tones and mouth-watering food photography.',
    descAr: 'محتوى سوشيال ميديا شهي لمطعم عربي تقليدي. ألوان دافئة وتصوير طعام احترافي.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Restaurant', 'Food'],
    tagsAr: ['سوشيال ميديا', 'مطعم', 'أغذية'],
    image:  'assets/projects/p9/Thumbnail - Size 9 copy-opt.jpg',
    images: imgs('p9', 'Presentation-9', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#1a0800 0%,#2a1200 50%,#120600 100%)',
  },

  {
    id: 21,
    title: 'Social Media — Sun Plus Juices',
    titleAr: 'سوشيال ميديا — صن بلس للعصائر',
    desc: 'Vibrant and energetic social media for Sun Plus, a fresh juice and beverages brand. Bold yellows and tropical product visuals.',
    descAr: 'سوشيال ميديا نابض لعلامة صن بلس للعصائر الطازجة. ألوان صفراء جريئة وصور منتجات استوائية.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Juice', 'FMCG'],
    tagsAr: ['سوشيال ميديا', 'عصائر', 'مواد غذائية'],
    image:  'assets/projects/p10/Thumbnail - Size 10 copy-opt.jpg',
    images: imgs('p10', 'Presentation-10', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#1a1200 0%,#2a1e00 50%,#120e00 100%)',
  },

  {
    id: 22,
    title: 'Social Media — Tech Brand Campaign',
    titleAr: 'سوشيال ميديا — حملة براند تقني',
    desc: 'High-impact social media campaign for an Egyptian tech brand. Bold red visuals, product showcases and engagement-driven content.',
    descAr: 'حملة سوشيال ميديا قوية لعلامة تقنية مصرية. تصاميم حمراء جريئة وعروض منتجات ومحتوى تفاعلي.',
    cat: 'Social', year: '2024',
    tags: ['Social Media', 'Tech', 'Egypt'],
    tagsAr: ['سوشيال ميديا', 'تقنية', 'مصر'],
    image:  'assets/projects/P11/Presentation 11 copy-opt.jpg',
    images: imgs('P11', 'Presentation-11', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#1a0000 0%,#2a0505 50%,#120000 100%)',
  },

  // ── سوشيال ميديا — مشاريع الخليج ──────────────────

  {
    id: 23,
    title: 'Social Media — Al Yamamah',
    titleAr: 'سوشيال ميديا — اليمامة',
    desc: 'Social media content for Al Yamamah, a Saudi services company. Includes Ramadan campaigns, religious posts and promotional content.',
    descAr: 'محتوى سوشيال ميديا لشركة اليمامة السعودية. يشمل حملات رمضان والمحتوى الديني والترويجي.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Saudi Arabia', 'Ramadan'],
    tagsAr: ['سوشيال ميديا', 'السعودية', 'رمضان'],
    image: 'assets/projects/p23 Al Yamamah Social media/Artboard 1-opt.jpg',
    images: flist('p23 Al Yamamah Social media', [
      'Artboard 1.png','Artboard 2.png','Artboard 3.png',
      'Artboard 4.png','Artboard 5.png','Artboard 6.png',
      'Artboard 1-.png','Artboard 2-.png',
      '-دعاء وحديث 28 copy2.png','-دعاء وحديث 28 copy3.png',
      'افطار copy.png','حملة عمرة رمضان copy2.png'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#0d0520 0%,#1a0a35 50%,#0f1040 100%)',
    saudi: true,
  },

  {
    id: 27,
    title: 'Social Media — Luini Bakery',
    titleAr: 'سوشيال ميديا — لويني بيكري',
    desc: 'Social media campaign for Luini Bakery, a Saudi artisan bakery. Rich warm tones and appetising imagery.',
    descAr: 'حملة سوشيال ميديا لمخبز لويني السعودي. ألوان دافئة وصور شهية.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Bakery', 'F&B', 'Saudi Arabia'],
    tagsAr: ['سوشيال ميديا', 'مخبز', 'أغذية', 'السعودية'],
    image: 'assets/projects/p27 luini Bakery/Artboard 1-opt.jpg',
    images: flist('p27 luini Bakery', [
      'Artboard 1.png','Artboard 2.png','Artboard 3.png','Artboard 4.png',
      '51.png','52.png',
      '2.jpeg','3.jpeg','4.jpeg','5.jpeg','6.jpeg','7.jpeg','8.jpeg',
      'luini.sa-20250113_110610-136167611.jpg',
      'luini.sa-20250121_115936-3264591470.jpg',
      'luini.sa-20250130_182414-272922730.jpg'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#1a0a00 0%,#2a1205 50%,#120800 100%)',
    saudi: true,
  },

  {
    id: 36,
    title: 'Social Media — Eilaf Covers',
    titleAr: 'سوشيال ميديا — إيلاف غلافات',
    desc: 'Website and social media cover designs for Eilaf, a Saudi company. Professional banner layouts with brand consistency.',
    descAr: 'تصاميم غلافات موقع ويب وسوشيال ميديا لشركة إيلاف السعودية.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Cover Design', 'Saudi Arabia'],
    tagsAr: ['سوشيال ميديا', 'غلافات', 'السعودية'],
    image: 'assets/projects/p36 Eilaf Cover web/Artboard 1-opt.jpg',
    images: flist('p36 Eilaf Cover web', [
      'Artboard 1.png','Artboard 2.png','Artboard 3.png','Artboard 4.png',
      'Artboard 5.png','Artboard 6.png','Artboard 7.png','Artboard 8.png',
      'Artboard 9.png','Artboard 10.png'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#0d0520 0%,#1a0a35 50%,#0f1040 100%)',
    saudi: true,
  },

  {
    id: 361,
    title: 'Social Media — Elaf Posts',
    titleAr: 'سوشيال ميديا — إلاف بوستات',
    desc: 'Social media posts series for Elaf, a Saudi company. Consistent visual language across all posts.',
    descAr: 'سلسلة بوستات سوشيال ميديا لشركة إلاف السعودية.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Posts', 'Saudi Arabia'],
    tagsAr: ['سوشيال ميديا', 'بوستات', 'السعودية'],
    image: 'assets/projects/p36 Elaf post/Artboard 1-opt.jpg',
    images: flist('p36 Elaf post', [
      'Artboard 1.png','Artboard 2.png','Artboard 3.png','Artboard 4.png',
      'Artboard 5.png','Artboard 6.png','Artboard 7.png','Artboard 8.png'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#0d0520 0%,#1a0a35 50%,#0f1040 100%)',
    saudi: true,
  },

  {
    id: 37,
    title: 'Social Media — Al Afdal',
    titleAr: 'سوشيال ميديا — الأفضل',
    desc: 'Social media designs for Al Afdal, a Saudi brand. Bold graphics and engaging visual storytelling.',
    descAr: 'تصاميم سوشيال ميديا لعلامة الأفضل السعودية. جرافيك جريء وسرد بصري جذاب.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Saudi Arabia'],
    tagsAr: ['سوشيال ميديا', 'السعودية'],
    image: 'assets/projects/p37 Alfdal posts/post 00 copy-opt.jpg',
    images: flist('p37 Alfdal posts', [
      'post 00 copy.png','Artboard 1.png','Artboard 2.png','Artboard 3.png'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#0d0520 0%,#1a0a35 50%,#0f1040 100%)',
    saudi: true,
  },

  {
    id: 39,
    title: 'Social Media — Lushly',
    titleAr: 'سوشيال ميديا — لوشلي',
    desc: 'Elegant social media posts for Lushly, a Saudi lifestyle brand. Soft tones and refined design aesthetic.',
    descAr: 'بوستات سوشيال ميديا أنيقة لعلامة لوشلي السعودية. ألوان ناعمة وتصميم راقٍ.',
    cat: 'Social', year: '2025',
    tags: ['Social Media', 'Lifestyle', 'Saudi Arabia'],
    tagsAr: ['سوشيال ميديا', 'لايف ستايل', 'السعودية'],
    image: 'assets/projects/p39 Lushly Posts/Artboard 1-opt.jpg',
    images: flist('p39 Lushly Posts', [
      'Artboard 1.png','Artboard 2.png','Artboard 3.png',
      'Artboard 4.png','Artboard 5.png','Artboard 6.png'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#0d0520 0%,#1a0a35 50%,#0f1040 100%)',
    saudi: true,
  },

  {
    id: 33,
    title: 'Web Design — Resalah',
    titleAr: 'تصميم ويب — رسالة',
    desc: 'Website UI design for Resalah, a Saudi professional services company. Clean layouts with strong Arabic typography.',
    descAr: 'تصميم واجهة موقع ويب لشركة رسالة السعودية للخدمات المهنية.',
    cat: 'Branding', year: '2025',
    tags: ['Web Design', 'UI', 'Saudi Arabia'],
    tagsAr: ['تصميم ويب', 'واجهة مستخدم', 'السعودية'],
    image: 'assets/projects/p33 Resalah Web/Artboard 1-opt.jpg',
    images: flist('p33 Resalah Web', [
      'Artboard 1.png','Artboard 2.png','Artboard 3.png',
      'Artboard 3 - Copy.png','Artboard 4.png','Artboard 5.png',
      'Artboard 6.png','Artboard 7.png','Artboard8.png','5.jpeg'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#061014 0%,#0a1c28 50%,#060c12 100%)',
    saudi: true,
  },

  // ══════════════════════════════════════════════════════
  //  مطبوعات
  // ══════════════════════════════════════════════════════

  {
    id: 5,
    title: 'Company Profile — Etching',
    titleAr: 'ملف الشركة — إيتشينج',
    desc: 'Premium company profile for Etching, an Egyptian creative production company.',
    descAr: 'ملف شركة احترافي لشركة إيتشينج المصرية للإنتاج الإبداعي.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Print', 'Egypt'],
    tagsAr: ['ملف شركة', 'مطبوعات', 'مصر'],
    image:  'assets/projects/P12 - PROFILE/Thumbnail - Size 12 copy-opt.jpg',
    images: imgs('P12 - PROFILE', 'Presentation-12', 13),
    link: 'https://www.behance.net/gallery/224062339/Company-Profile-Etching',
    _bg: 'linear-gradient(135deg,#060e14 0%,#0a1428 50%,#060a12 100%)',
  },

  {
    id: 6,
    title: 'Company Profile — DOJO',
    titleAr: 'ملف الشركة — دوجو',
    desc: 'Corporate profile for DOJO, a Saudi martial arts and fitness training center with Japanese branding concept.',
    descAr: 'ملف مؤسسي لمركز دوجو السعودي للفنون القتالية واللياقة بمفهوم بصري ياباني.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Sports', 'Saudi Arabia', 'Japan'],
    tagsAr: ['ملف شركة', 'رياضة', 'السعودية', 'اليابان'],
    image:  'assets/projects/P13 - PROFILE/Thumbnail - Size 13 copy-opt.jpg',
    images: imgs('P13 - PROFILE', 'Presentation-13', 13),
    link: 'https://www.behance.net/gallery/224062399/Company-Profile-DOJO',
    _bg: 'linear-gradient(135deg,#060e16 0%,#0a1628 50%,#060810 100%)',
    saudi: true,
  },

  {
    id: 7,
    title: 'Company Profile — Grasse',
    titleAr: 'ملف الشركة — غراس',
    desc: 'Luxury company profile for Grasse, an Emirati high-end fragrance and lifestyle brand.',
    descAr: 'ملف شركة فاخر لعلامة غراس الإماراتية للعطور واللايف ستايل.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Luxury', 'UAE'],
    tagsAr: ['ملف شركة', 'فاخر', 'الإمارات'],
    image:  'assets/projects/P14 - PROFILE/Thumbnail - Size 14 copy-opt.jpg',
    images: ['assets/projects/P14 - PROFILE/images/Presentation 14.png'],
    link: 'https://www.behance.net/gallery/241299397/Company-Profile-Grasse',
    _bg: 'linear-gradient(135deg,#1a1000 0%,#2a1e04 50%,#120e00 100%)',
    uae: true,
  },

  {
    id: 8,
    title: 'Company Profile — Thailand Tourism',
    titleAr: 'ملف الشركة — سياحة تايلاند',
    desc: 'Travel and tourism company profile. Rich visual narrative with an immersive editorial layout.',
    descAr: 'ملف شركة سياحة. سرد بصري غني بتخطيط تحريري غامر.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Tourism', 'Print'],
    tagsAr: ['ملف شركة', 'سياحة', 'مطبوعات'],
    image:  'assets/projects/P15 - PROFILE/Thumbnail - Size 15 copy-opt.jpg',
    images: imgs('P15 - PROFILE', 'Presentation-15', 13),
    link: 'https://www.behance.net/gallery/224062449/Company-Profile-Thailand',
    _bg: 'linear-gradient(135deg,#0a1810 0%,#0d2015 50%,#060c0a 100%)',
  },

  // ── مطبوعات — مشاريع الخليج ──────────────────────

  {
    id: 24,
    title: 'Company Profile — Al Yamamah',
    titleAr: 'ملف الشركة — اليمامة',
    desc: 'Professional company profile for Al Yamamah Corporation, Saudi Arabia. High-end print design with bilingual content.',
    descAr: 'ملف شركة احترافي لمؤسسة اليمامة السعودية. تصميم طباعي راقٍ بمحتوى ثنائي اللغة.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Print', 'Saudi Arabia'],
    tagsAr: ['ملف شركة', 'مطبوعات', 'السعودية'],
    image: 'assets/projects/P24 Profile Company Al Yamamh/mOCKUP غشةشةشا copy-opt.jpg',
    images: flist('P24 Profile Company Al Yamamh', ['mOCKUP غشةشةشا copy.png']),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#060e14 0%,#0a1428 50%,#060a12 100%)',
    saudi: true,
  },

  {
    id: 25,
    title: 'Corporate Brochure — Al Yamamah Crosswell',
    titleAr: 'بروشور — اليمامة كروسويل',
    desc: 'Corporate brochure for Al Yamamah Crosswell, Saudi Arabia. Clean grid-based editorial layout.',
    descAr: 'بروشور مؤسسي لشركة اليمامة كروسويل السعودية. تخطيط شبكي نظيف.',
    cat: 'Print', year: '2025',
    tags: ['Brochure', 'Print', 'Saudi Arabia'],
    tagsAr: ['بروشور', 'مطبوعات', 'السعودية'],
    image: 'assets/projects/p25 Alyamamh Crosswel/Artboard 1-opt.jpg',
    images: flist('p25 Alyamamh Crosswel', [
      'Artboard 1.png','Artboard 2.png','Artboard 3.png',
      'Artboard 4.png','Artboard 5.png','Artboard 6.png','Artboard 7.png'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#060e14 0%,#0a1428 50%,#060a12 100%)',
    saudi: true,
  },

  {
    id: 26,
    title: 'Company Profile — Al Yamamah Crosswell Vol.2',
    titleAr: 'ملف الشركة — اليمامة كروسويل Vol.2',
    desc: 'Second edition company profile for Al Yamamah Crosswell. Updated brand direction with premium editorial approach.',
    descAr: 'الإصدار الثاني من ملف شركة اليمامة كروسويل بتوجه براندي محدّث.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Print', 'Saudi Arabia'],
    tagsAr: ['ملف شركة', 'مطبوعات', 'السعودية'],
    image: 'assets/projects/p26 Alyamamh Crosswel/Artboard 1-opt.jpg',
    images: flist('p26 Alyamamh Crosswel', [
      'Artboard 1.png','Artboard 2.png','Artboard 3.png',
      'Artboard 4.png','Artboard 5.png','Artboard 6.png'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#060e14 0%,#0a1428 50%,#060a12 100%)',
    saudi: true,
  },

  {
    id: 262,
    title: 'Business Card — Hazim',
    titleAr: 'بطاقة أعمال — حازم',
    desc: 'Premium business card design for Hazim, a Saudi professional. Refined typography and high-quality print finish.',
    descAr: 'تصميم بطاقة أعمال راقية للأستاذ حازم. طباعة فاخرة وبصمة مميزة.',
    cat: 'Print', year: '2025',
    tags: ['Business Card', 'Print', 'Saudi Arabia'],
    tagsAr: ['بطاقة أعمال', 'مطبوعات', 'السعودية'],
    image: 'assets/projects/p26 Hazim Busniess Card/mOCKUP1-opt.jpg',
    images: flist('p26 Hazim Busniess Card', [
      'mOCKUP1.png','mOCKUP 4.png','02 copy5.png',
      'WhatsApp Image 2026-05-02 at 1.56.42 PM.jpeg'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#080808 0%,#141414 50%,#0a0a0a 100%)',
    saudi: true,
  },

  {
    id: 28,
    title: 'Business Card — Rio Media',
    titleAr: 'بطاقة أعمال — ريو ميديا',
    desc: 'Sleek business card for Rio Media, a Saudi creative agency.',
    descAr: 'بطاقة أعمال أنيقة لوكالة ريو ميديا الإبداعية السعودية.',
    cat: 'Print', year: '2025',
    tags: ['Business Card', 'Print', 'Saudi Arabia'],
    tagsAr: ['بطاقة أعمال', 'مطبوعات', 'السعودية'],
    image: 'assets/projects/p28 Rio media Bussiness Card/0 copy-opt.jpg',
    images: flist('p28 Rio media Bussiness Card', ['0 copy.png']),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#080808 0%,#141414 50%,#0a0a0a 100%)',
    saudi: true,
  },

  {
    id: 29,
    title: 'Company Profile — Rio Service',
    titleAr: 'ملف الشركة — ريو للخدمات',
    desc: 'Company profile for Rio Service Company, a Saudi professional services firm.',
    descAr: 'ملف شركة لشركة ريو للخدمات المهنية السعودية.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Print', 'Saudi Arabia'],
    tagsAr: ['ملف شركة', 'مطبوعات', 'السعودية'],
    image: 'assets/projects/P29 Rio service profile comapny/RIO SER copy-opt.jpg',
    images: flist('P29 Rio service profile comapny', ['RIO SER copy.png']),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#060e14 0%,#0a1428 50%,#060a12 100%)',
    saudi: true,
  },

  {
    id: 30,
    title: 'Brochure — Rio Print',
    titleAr: 'بروشور — ريو للطباعة',
    desc: 'High-end print brochure for Rio, a Saudi print and media company.',
    descAr: 'بروشور مطبوعات فاخر لشركة ريو السعودية للطباعة والإعلام.',
    cat: 'Print', year: '2025',
    tags: ['Brochure', 'Print', 'Saudi Arabia'],
    tagsAr: ['بروشور', 'مطبوعات', 'السعودية'],
    image: 'assets/projects/p30 Rio pourshure print/brochure_1101510231 - Copy copy-opt.jpg',
    images: flist('p30 Rio pourshure print', ['brochure_1101510231 - Copy copy.jpg']),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#060e14 0%,#0a1428 50%,#060a12 100%)',
    saudi: true,
  },

  {
    id: 31,
    title: 'Company Profile — Resalah Landscape',
    titleAr: 'ملف الشركة — رسالة أفقي',
    desc: 'Landscape-format company profile for Resalah, a Saudi professional services company.',
    descAr: 'ملف شركة بتخطيط أفقي لشركة رسالة السعودية.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Print', 'Saudi Arabia'],
    tagsAr: ['ملف شركة', 'مطبوعات', 'السعودية'],
    image: 'assets/projects/p31 Resalah profile Landscape/m2-opt.jpg',
    images: flist('p31 Resalah profile Landscape', ['m2.png']),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#060e14 0%,#0a1428 50%,#060a12 100%)',
    saudi: true,
  },

  {
    id: 32,
    title: 'Company Profile — Resalah Arabic',
    titleAr: 'ملف الشركة — رسالة عربي',
    desc: 'Arabic-language company profile for Resalah, Saudi Arabia. RTL layout with premium typography.',
    descAr: 'ملف شركة باللغة العربية لشركة رسالة السعودية. تخطيط RTL وطباعة راقية.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Print', 'Arabic', 'Saudi Arabia'],
    tagsAr: ['ملف شركة', 'مطبوعات', 'عربي', 'السعودية'],
    image: 'assets/projects/p32 Resalah Profile AR/m1-opt.jpg',
    images: flist('p32 Resalah Profile AR', ['m1.png']),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#060e14 0%,#0a1428 50%,#060a12 100%)',
    saudi: true,
  },

  {
    id: 34,
    title: 'Company Profile — Resalah Interior Design',
    titleAr: 'ملف الشركة — رسالة للتصميم الداخلي',
    desc: 'Sophisticated company profile for Resalah Interior Design, a Saudi luxury interiors firm. Full editorial treatment across 16 spreads.',
    descAr: 'ملف شركة متكامل لشركة رسالة للتصميم الداخلي الفاخر. 16 صفحة بأسلوب تحريري راقٍ.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Interior Design', 'Saudi Arabia'],
    tagsAr: ['ملف شركة', 'تصميم داخلي', 'السعودية'],
    image: 'assets/projects/p34 Resalah Profile Introir design/التصميم الداخلي-opt.jpg',
    images: flist('p34 Resalah Profile Introir design', [
      'التصميم الداخلي.png',
      'Artboard 1.png','Artboard 2.png','Artboard 3.png','Artboard 4.png',
      'Artboard 5.png','Artboard 6.png','Artboard 7.png','Artboard 8.png',
      'Artboard 9.png','Artboard 10.png','Artboard 11.png','Artboard 12.png',
      'Artboard 13.png','Artboard 14.png','Artboard 15.png','Artboard 16.png'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#060e14 0%,#0a1428 50%,#060a12 100%)',
    saudi: true,
  },

  {
    id: 35,
    title: 'Company Profile — Resalah Aluminium',
    titleAr: 'ملف الشركة — رسالة للألمنيوم',
    desc: 'Complete company profile for Resalah Aluminium, a Saudi manufacturing company. Multi-page document with full brand identity.',
    descAr: 'ملف شركة متكامل لشركة رسالة للألمنيوم السعودية. وثيقة ضخمة تغطي الهوية البصرية الكاملة.',
    cat: 'Print', year: '2025',
    tags: ['Company Profile', 'Industrial', 'Saudi Arabia'],
    tagsAr: ['ملف شركة', 'صناعي', 'السعودية'],
    image: 'assets/projects/p35 Resalah Profile Alumunium/Artboard 2-opt.jpg',
    images: flist('p35 Resalah Profile Alumunium', [
      'Artboard 2.png','Artboard 3.png','Artboard 4.png','Artboard 5.png',
      'Artboard 6.png','Artboard 7.png','Artboard 8.png','Artboard 9.png',
      'Artboard 10.png','Artboard 11.png','Artboard 12.png','Artboard 13.png',
      'Artboard ٢٠ copy 2.png','Artboard ٢٠ copy 3.png','Artboard ٢٠ copy 4.png',
      'Artboard ٢٠ copy 5.png','Artboard ٢٠ copy 6.png','Artboard ٢٠ copy 7.png',
      'Artboard ٢٠ copy 8.png','Artboard ٢٠ copy 9.png','Artboard ٢٠ copy 10.png'
    ]),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#060e14 0%,#0a1428 50%,#060a12 100%)',
    saudi: true,
  },

  // ══════════════════════════════════════════════════════
  //  هوية بصرية وشعارات
  // ══════════════════════════════════════════════════════

  {
    id: 9,
    title: 'Brand Identity — Souq Mazad',
    titleAr: 'هوية بصرية — سوق مزاد',
    desc: 'Full brand identity for Souq Mazad, an Egyptian online auction marketplace.',
    descAr: 'هوية بصرية متكاملة لمنصة سوق مزاد المصرية للمزادات الإلكترونية.',
    cat: 'Branding', year: '2025',
    tags: ['Brand Identity', 'Logo', 'Digital'],
    tagsAr: ['هوية بصرية', 'شعار', 'رقمي'],
    image:  'assets/projects/P16 - logo guideline/Thumbnail - Size 16 copy-opt.jpg',
    images: [],
    link: 'https://www.behance.net/gallery/224062067/Souq-Mazad-Visual-Identity',
    _bg: 'linear-gradient(135deg,#07051c 0%,#100a30 50%,#080618 100%)',
  },

  {
    id: 10,
    title: 'Brand Identity — DORUN',
    titleAr: 'هوية بصرية — دورن',
    desc: 'Complete logo and brand guidelines for DORUN, a sports and fitness brand.',
    descAr: 'شعار ودليل هوية متكامل لعلامة دورن الرياضية.',
    cat: 'Branding', year: '2025',
    tags: ['Logo', 'Brand Identity', 'Sports'],
    tagsAr: ['شعار', 'هوية بصرية', 'رياضة'],
    image:  'assets/projects/P17 - logo guideline/Thumbnail - Size 17 copy-opt.jpg',
    images: imgs('P17 - logo guideline', 'Presentation-17', 13),
    link: 'https://www.behance.net/gallery/224062141/Logo-Guideline-DORUN',
    _bg: 'linear-gradient(135deg,#07051c 0%,#100a30 50%,#080618 100%)',
  },

  {
    id: 11,
    title: 'Brand Identity — GST',
    titleAr: 'هوية بصرية — GST',
    desc: 'Brand identity and logo guidelines for GST, an Egyptian professional services company. Includes sub-brand identities for Al Arzaq Billah and Monterey Bay.',
    descAr: 'هوية بصرية وشعار لشركة GST المصرية للخدمات المهنية. تشمل الهويات الفرعية: الأرزاق بالله ومونتيري باي.',
    cat: 'Branding', year: '2025',
    tags: ['Logo', 'Brand Identity', 'Corporate', 'Egypt'],
    tagsAr: ['شعار', 'هوية بصرية', 'مؤسسي', 'مصر'],
    image:  'assets/projects/P18 - logo guideline/Thumbnail - Size 18 copy-opt.jpg',
    images: imgs('P18 - logo guideline', 'Presentation-18', 13),
    link: 'https://www.behance.net/gallery/224062197/Logo-Guideline-GST',
    _bg: 'linear-gradient(135deg,#07051c 0%,#100a30 50%,#080618 100%)',
  },

  {
    id: 12,
    title: 'Brand Identity — Monterey Bay',
    titleAr: 'هوية بصرية — مونتيري باي',
    desc: 'Visual identity for Monterey Bay, an Egyptian premium seafood brand under the GST group.',
    descAr: 'هوية بصرية لعلامة مونتيري باي المصرية للمأكولات البحرية الفاخرة — تحت مظلة مجموعة GST.',
    cat: 'Branding', year: '2025',
    tags: ['Logo', 'Brand Identity', 'F&B', 'Egypt'],
    tagsAr: ['شعار', 'هوية بصرية', 'أغذية', 'مصر'],
    image:  'assets/projects/P19 - logo guideline/Thumbnail - Size 19 copy-opt.jpg',
    images: imgs('P19 - logo guideline', 'Presentation-19', 13),
    link: 'https://www.behance.net/gallery/224062257/Logo-Guideline-Monterey-Bay',
    _bg: 'linear-gradient(135deg,#07051c 0%,#100a30 50%,#080618 100%)',
  },

  {
    id: 13,
    title: 'Brand Identity — Al Arzaq Billah',
    titleAr: 'هوية بصرية — الأرزاق بالله',
    desc: 'Arabic brand identity for Al Arzaq Billah, an Egyptian traditional food brand under the GST group.',
    descAr: 'هوية بصرية عربية أصيلة لعلامة الأرزاق بالله المصرية للأغذية — تحت مظلة مجموعة GST.',
    cat: 'Branding', year: '2025',
    tags: ['Logo', 'Arabic Brand', 'Food', 'Egypt'],
    tagsAr: ['شعار', 'براند عربي', 'أغذية', 'مصر'],
    image:  'assets/projects/P20 - logo guideline/Thumbnail - Size 20 copy-opt.jpg',
    images: imgs('P20 - logo guideline', 'Presentation-20', 13),
    link: 'https://www.behance.net/gallery/224062313/Logo-Guideline',
    _bg: 'linear-gradient(135deg,#07051c 0%,#100a30 50%,#080618 100%)',
  },

  {
    id: 14,
    title: 'Brand Identity — KEMETS',
    titleAr: 'هوية بصرية — KEMETS',
    desc: 'Bold visual identity for KEMETS, an Egyptian brand featuring the Hottie street food and beverages line.',
    descAr: 'هوية بصرية جريئة لعلامة KEMETS المصرية — تضم خط منتجات هوتي لطعام الشارع والمشروبات.',
    cat: 'Branding', year: '2025',
    tags: ['Logo', 'Brand Identity', 'F&B', 'Egypt'],
    tagsAr: ['شعار', 'هوية بصرية', 'أغذية', 'مصر'],
    image:  'assets/projects/P21 - logo guideline/Thumbnail - 21 copy-opt.jpg',
    images: imgs('P21 - logo guideline', 'Presentation-21', 13),
    link: 'https://www.behance.net/gallery/224062353/Logo-Guideline-Hottie',
    _bg: 'linear-gradient(135deg,#07051c 0%,#100a30 50%,#080618 100%)',
  },

  {
    id: 15,
    title: 'Brand Identity — Mosaic',
    titleAr: 'هوية بصرية — موزاييك',
    desc: 'Logo and brand identity for Mosaic, an interior design studio.',
    descAr: 'شعار وهوية بصرية لاستوديو موزاييك للتصميم الداخلي.',
    cat: 'Branding', year: '2025',
    tags: ['Logo', 'Brand Identity', 'Interior'],
    tagsAr: ['شعار', 'هوية بصرية', 'ديكور'],
    image:  'assets/projects/P22 - logo guideline/images/Presentation-22_01-opt.jpg',
    images: imgs('P22 - logo guideline', 'Presentation-22', 13),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#07051c 0%,#100a30 50%,#080618 100%)',
  },

  {
    id: 38,
    title: 'Brand Identity — Lushly',
    titleAr: 'هوية بصرية — لوشلي',
    desc: 'Brand logo and visual identity for Lushly, a Saudi lifestyle brand.',
    descAr: 'شعار وهوية بصرية لعلامة لوشلي السعودية.',
    cat: 'Branding', year: '2025',
    tags: ['Logo', 'Brand Identity', 'Lifestyle', 'Saudi Arabia'],
    tagsAr: ['شعار', 'هوية بصرية', 'لايف ستايل', 'السعودية'],
    image: 'assets/projects/p38 Lushly Logo/logo Identity copy-opt.jpg',
    images: flist('p38 Lushly Logo', ['logo Identity copy.png']),
    link: 'https://www.behance.net/ahmedhassanbahaa',
    _bg: 'linear-gradient(135deg,#07051c 0%,#100a30 50%,#080618 100%)',
    saudi: true,
  },

];
